#pragma once

#include "NativeGameplayTags.h"

namespace EffectTags
{
	// ControlEffectTags
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interact);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UsingSkill);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConsumingItem);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Death);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dash);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Parry);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DashInvincible);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DashAttackPossible);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UsingDash);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UsingParry);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UsingZoneya);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UsingTeleport);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(LockOn);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Groggy);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Parried);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stiffness);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flew);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StandingUp);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ControlDebuff);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ControlBuff);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stun);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(PreStun);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Silence);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Confused);
	
	// StatusEffectTags
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Running);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walking);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StatusDebuff);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StatusBuff);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slow);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackDown);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Burn);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Poison);

	// AIEffectTags
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Idle);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Suspicious);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Alert);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combat);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Patrol);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Return);
}

namespace StatTags
{
	// BaseStatTags
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BaseStat);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Level);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(LIFE);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(STR);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SPL);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(END);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BaseAttackPower);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BaseMagicPower);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BaseMaxHealth);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BaseMaxStamina);

	// Base -> Battle Coefficients
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StatCoefficient);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackPowerCoefficient);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagicPowerCoefficient);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxHealthCoefficient);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxStaminaCoefficient);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SoftCapThreshold);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(PostSoftCapMultiplier);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(LevelUpCoefficientB);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(LevelUpCoefficientC);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(LevelUpCoefficientD);
	
	// BattleStatTags
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BattleStat);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxHealth);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxStamina);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackPower);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SubAttackPower);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagicPower);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StaminaRecoveryRate);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SpeedCoefficient);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Defense);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxShield);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxGroggyGauge);
	
	// VariableStatTags
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(VariableStat);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Health);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stamina);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shield);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GroggyGauge);
}

namespace SkillGroupTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BaseAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeaponSkill);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagicSkill);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DashAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dash);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Parry);

	// Boss1
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SuperAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SpecialAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(EvadeAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(JumpAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RangedAttack);

	// Boss2 Skill Group Tag
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2BaseAttack1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2BaseAttack2);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2Circling);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2DashAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2EvadeAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2TeleportAttack);

	// Boss4
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack1Start);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack1First);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack1Second);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack1Third);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack2);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack3);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack3First);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack3Second);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack3Third);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack3Fourth);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4FlameStrike);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4SpawnClone);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4CloneStart);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4InfernoSpike);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4HellfireFall);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4BlazeSphere);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4BackDash);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4Teleport);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4RandomMove);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4EvadeAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4RisingWall);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4SlashWave);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4SpawnClonePhase2);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4ClonePhase2_1First);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4ClonePhase2_1Second);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4ClonePhase2_1Third);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4ClonePhase2_2First);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4ClonePhase2_2Second);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4ClonePhase2_2Third);
}

namespace SkillTags
{
	// Player
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BaseAttackSword1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BaseAttackSword2);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BaseAttackSword3);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BaseAttackAxe1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BaseAttackAxe2);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BaseAttackAxe3);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BaseAttackClaw1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BaseAttackClaw2);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BaseAttackClaw3);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BaseAttackClaw4);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DashAttackSword);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DashAttackClaw);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DashAttackAxe);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeaponSkillSword1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeaponSkillAxe1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeaponSkillClaw1);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BaseAttackSpear1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(PlayerDash);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(PlayerParry);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagicLaserSkill);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagicRailGunSkill);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagicFireBallSkill);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagicZoneyaSkill);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagicInfiniteStaminaSkill);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagicTeleportSkill);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagicItemScanningSkill);	

	// NomalMonster
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AxeSkeletonComboAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SwordSkeletonBaseAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DualBladeSkeletonBaseAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DualBladeSkeletonJumpAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(KnifeThrow);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WoodSwiping);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WoodHurricaneKick);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MinionBaseAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GunMinionFire);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GolemSmash);


	// Boss1
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss1LevelStart);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss1Parried);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss1BaseAttack1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss1BaseAttack2);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss1BaseAttack3);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss1SuperAttack1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss1SuperAttack2);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss1SpecialAttack1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss1SpecialAttack2);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss1EvadeAttack);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss1JumpAttack);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss1RangedAttack);

	// Boss2
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2LevelStart);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2BaseAttack1First);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2BaseAttack1Second);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2BaseAttack1Third);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2BaseAttack1Fourth);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2BaseAttack2First);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2BaseAttack2Second);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2BaseAttack2Third);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2BaseAttack2Fourth);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2BaseAttack2Fifth);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2Circling);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2DashAttackFirst);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2DashAttackSecond);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2DashAttackThird);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2DashAttackBFirst);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2DashAttackBSecond);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2EvadeAttackFirst);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2EvadeAttackSecond);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2Dash);

	// Boss3
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss3LevelStart);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss3BaseAttack1first);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss3BaseAttack1second);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss3BaseAttack1third);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss3BaseAttack2first);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss3BaseAttack2second);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss3BaseAttack3first);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss3BaseAttack3second);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss3RockThrow);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss3TurningAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss3GroundFall);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss3Grab);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss3GrabAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss3RushAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss3JumpAttack);

	// Boss4
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4BaseAttackFirst);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4BaseAttackSecond);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack1Start);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack1First);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack1Second);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack1Third);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4FlameStrike);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4SpawnClone);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4CloneStart);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4InfernoSpike);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4HellfireFall);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4BlazeSphere);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4BackDash);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4Teleport);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4RandomMove);

	/// Boss4_2
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4Phase2LevelStart);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack2First);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack2Second);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack2Third);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack2Fourth);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack2Fifth);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack2Sixth);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack2Seventh);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack2Eighth);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack3First);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack3Second);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack3Third);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4WeaponAttack3Fourth);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4EvadeAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4RisingWall);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4SlashWaveFirst);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4SlashWaveSecond);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4SlashWaveThird);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4SpawnClonePhase2);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4ClonePhase2_1First);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4ClonePhase2_1Second);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4ClonePhase2_1Third);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4ClonePhase2_2First);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4ClonePhase2_2Second);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4ClonePhase2_2Third);

	//Boss5
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss5PeckingAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss5ZoneyaAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss5ElectricAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss5SpawnEnemyAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss5ProjectileAttack);
}

namespace PawnTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ProtoNormal);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ProtoElite);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ProtoBoss);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ArrowProto);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AxeSkeleton);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SwordSkeleton);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DualBladeSkeleton);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(KnifeSkeleton);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Wood);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Minion);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GunMinion);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(EliteGolem);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss2);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss3);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4Clone);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss4Clone2Phase);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss5);

}

namespace ItemTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemBase);

	//Equippable Item Tags
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(EquippableItem);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeaponItem);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BasicWeapon);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SwordWeapon);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AxeWeapon);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ClawWeapon);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HammerWeapon);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillItem);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RailGunSkillItem);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FireBallSkillItem);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TeleportSkillItem);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ZoneyaSkillItem);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InfiniteStaminaSkillItem);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemScanningSkillItem);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AccessoryItem);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RingOfHealthAccessoryItem);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(NecklaceOfStaminaAccessoryItem);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(EaringOfAttackPowerAccessoryItem);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SlowImmuneAccessoryItem);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BurnImmuneAccessoryItem);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(PoisonImmuneAccessoryItem);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackDownImmuneAccessoryItem);

	//Consumable Item Tags
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConsumableItem);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Potion);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(PotionBoosted);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(PotionBoosted1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(PotionBoosted2);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(PotionBoosted3);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(PotionBoosted4);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(PotionBoosted5);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StaminaPotion);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Elixir);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(PoisonCure);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(BurnCure);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SlowCure);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackDownCure);

	//Other Item Tags
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(OtherItem);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Key);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(EnergyCore);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GolemHeart);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HintNote1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HintNote2);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HintNote3);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WitchDiary1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WitchDiary2);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WitchDiary3);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WitchDiary4);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AddMaxPotion);
}

namespace TraceTags
{
	// Axe
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HandRightAxe);

	// Claw
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HandLeftClaw);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HandRightClaw);
	
	// Sword
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HandRightSword);

	//Boss3
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Body);
}

namespace WorldActorTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemDropped);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(OpenableChestItem);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemContainer);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DyingHelper);
}